In [5]:
import sys
sys.path.insert(0, "/Users/rdhir/Documents/maxpreps_scraper")

from maxpreps_scraper.scraper import MaxPrepsScraper

In [9]:
scraper = MaxPrepsScraper()

df = scraper.get_contests(state='tx', sport='basketball', year='21-22', boys=False, cities = ['san antonio'])

df.head()

Scraping Schools for san antonio tx: 100%|██████████| 53/53 [00:03<00:00, 17.02 schools/s]

,Date,Team 1,Team 2,Team 1 Score,Team 2 Score,Outcome,Forfeit,Venue,Game Type,Team 1 Address,Team 1 City,Team 1 State,Team 1 Zipcode,Team 1 URL,Team 2 URL
0,11/5,Stevens,Smithson Valley,56.0,36.0,W,False,Away,Regular Season,600 Ellison N,San Antonio,TX,78251,/tx/san-antonio/stevens-falcons/basketball/gir...,/tx/spring-branch/smithson-valley-rangers/bask...
1,11/9,Stevens,MacArthur,56.0,35.0,W,False,Away,Regular Season,600 Ellison N,San Antonio,TX,78251,/tx/san-antonio/stevens-falcons/basketball/gir...,/tx/san-antonio/macarthur-brahmas/basketball/g...
2,11/12,Stevens,Sam Houston,53.0,35.0,W,False,Home,Tournament,600 Ellison N,San Antonio,TX,78251,/tx/san-antonio/stevens-falcons/basketball/gir...,/tx/san-antonio/sam-houston-hurricanes/basketb...
3,11/12,Stevens,Flower Mound,42.0,58.0,L,False,Home,Tournament,600 Ellison N,San Antonio,TX,78251,/tx/san-antonio/stevens-falcons/basketball/gir...,/tx/flower-mound/flower-mound-jaguars/basketba...
4,11/13,Stevens,Brennan,60.0,72.0,L,False,Home,Tournament,600 Ellison N,San Antonio,TX,78251,/tx/san-antonio/stevens-falcons/basketball/gir...,/tx/san-antonio/brennan-bears/basketball/girls...

In [8]:
df = scraper.get_rankings(state = 'de', sport = 'football', year = '23-24')

df.head(10)

    #              Team  Ovr.  Rating  Str.
0   1        Salesianum  12-1    48.3  25.2
1   2           Caravel  13-0    42.0  11.0
2   3        Middletown   8-4    37.6  28.1
3   4     Cape Henlopen   9-4    30.3  20.3
4   5             Dover   9-2    29.7  17.8
5   6   Hodgson Vo-Tech   7-4    29.2  25.3
6   7            Smyrna   4-7    24.9  29.1
7   8  Archmere Academy   9-4    24.3  11.7
8   9    Sussex Central   8-4    20.2  17.0
9  10            Howard   7-4    19.2  15.3